//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeneralEntities : DbContext
    {
        public GeneralEntities()
            : base("name=GeneralEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaseAlertResource> BaseAlertResource { get; set; }
        public DbSet<BaseLoggedInUsers> BaseLoggedInUsers { get; set; }
        public DbSet<gnl_arkadasima_oner> gnl_arkadasima_oner { get; set; }
        public DbSet<gnl_duyurular> gnl_duyurular { get; set; }
        public DbSet<gnl_grup_kullanici_tanimlari> gnl_grup_kullanici_tanimlari { get; set; }
        public DbSet<gnl_ileti> gnl_ileti { get; set; }
        public DbSet<gnl_ileti_alicilar> gnl_ileti_alicilar { get; set; }
        public DbSet<gnl_ileti_gelen> gnl_ileti_gelen { get; set; }
        public DbSet<gnl_kullanici_gruplari> gnl_kullanici_gruplari { get; set; }
        public DbSet<gnl_kullanici_sifre_sifirlama> gnl_kullanici_sifre_sifirlama { get; set; }
        public DbSet<gnl_kullanicilar> gnl_kullanicilar { get; set; }
        public DbSet<gnl_mail_service> gnl_mail_service { get; set; }
        public DbSet<gnl_ref_cinsiyet> gnl_ref_cinsiyet { get; set; }
        public DbSet<gnl_ref_uyelik_odeme_sekli> gnl_ref_uyelik_odeme_sekli { get; set; }
        public DbSet<gnl_ref_uyelik_tipleri> gnl_ref_uyelik_tipleri { get; set; }
        public DbSet<gnl_uye_kullanicilar> gnl_uye_kullanicilar { get; set; }
        public DbSet<gnl_uyelik_aktivasyon_mail_gonderi_tarihcesi> gnl_uyelik_aktivasyon_mail_gonderi_tarihcesi { get; set; }
        public DbSet<gnl_uyelik_bitis_bilgilendirme_mail_gonderi_tarihcesi> gnl_uyelik_bitis_bilgilendirme_mail_gonderi_tarihcesi { get; set; }
        public DbSet<gnl_uyelik_odeme_tipleri_tanimlari> gnl_uyelik_odeme_tipleri_tanimlari { get; set; }
        public DbSet<gnl_uyelik_paket_alimlari> gnl_uyelik_paket_alimlari { get; set; }
        public DbSet<log_mail> log_mail { get; set; }
    }
}
