//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gnl_ileti_alicilar
    {
        public System.Guid ileti_uid { get; set; }
        public System.Guid kullanici_uid { get; set; }
        public short alici_sirasi { get; set; }
        public string alici_tipi { get; set; }
    
        public virtual gnl_ileti gnl_ileti { get; set; }
    }
}
