//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gnl_uyelik_odeme_tipleri_tanimlari
    {
        public int odeme_tipi_id { get; set; }
        public Nullable<int> uyelik_tip_id { get; set; }
        public string odeme_tipi { get; set; }
        public Nullable<int> anket_sayisi { get; set; }
        public Nullable<int> katilimci_sayisi { get; set; }
        public Nullable<int> sure_ay { get; set; }
        public Nullable<decimal> ucret { get; set; }
    }
}
