//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gnl_kullanicilar
    {
        public System.Guid user_uid { get; set; }
        public string ad { get; set; }
        public string ikinci_ad { get; set; }
        public string soyad { get; set; }
        public byte[] sifre { get; set; }
        public string email { get; set; }
        public Nullable<System.Guid> grup_uid { get; set; }
        public string grup_adi { get; set; }
        public Nullable<bool> aktif { get; set; }
        public string aktivasyon_key { get; set; }
        public Nullable<bool> aktivasyon_ok { get; set; }
        public Nullable<bool> is_sistem_admin { get; set; }
        public Nullable<bool> dont_activate_purchase { get; set; }
        public Nullable<System.Guid> inserted_by { get; set; }
        public Nullable<System.DateTime> inserted_at { get; set; }
        public Nullable<System.Guid> updated_by { get; set; }
        public string updated_at { get; set; }
        public string UyelikKosullari { get; set; }
        public string Anket123Sorumluluklari { get; set; }
    }
}
