//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gnl_uyelik_paket_alimlari
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> user_uid { get; set; }
        public Nullable<System.Guid> grup_uid { get; set; }
        public Nullable<int> odeme_tipi_id { get; set; }
        public Nullable<System.DateTime> paket_alim_tarihi { get; set; }
        public Nullable<decimal> paket_fiyati { get; set; }
        public Nullable<int> anket_sayisi { get; set; }
        public Nullable<int> anket_basina_katilimci_sayisi { get; set; }
        public Nullable<int> paket_suresi { get; set; }
        public Nullable<System.DateTime> uyelik_bitis_tarihi { get; set; }
        public string telefonu { get; set; }
        public string cep_telefonu { get; set; }
        public string adres { get; set; }
        public string sirket_adi { get; set; }
        public string vergi_dairesi { get; set; }
        public string vergi_no { get; set; }
        public Nullable<int> grup_sirket_tipi_id { get; set; }
        public Nullable<int> odeme_sekli_id { get; set; }
        public Nullable<bool> aktive_edildi { get; set; }
        public Nullable<bool> kabul_edildi { get; set; }
        public string UyelikKosullari { get; set; }
        public string Anket123Sorumluluklari { get; set; }
        public Nullable<bool> fatura_kesildi { get; set; }
        public int islem_id { get; set; }
    }
}
