//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gnl_uye_kullanicilar
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> user_uid { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string telefonu { get; set; }
        public string cep_telefonu { get; set; }
        public string adres { get; set; }
        public string email { get; set; }
        public Nullable<System.Guid> grup_uid { get; set; }
        public string grup_adi { get; set; }
        public Nullable<System.DateTime> dogum_tarihi { get; set; }
        public Nullable<int> cinsiyet { get; set; }
        public string sirket_adi { get; set; }
        public string vergi_dairesi { get; set; }
        public string vergi_no { get; set; }
        public Nullable<int> grup_sirket_tipi_id { get; set; }
        public Nullable<bool> aktif { get; set; }
        public Nullable<System.DateTime> uye_baslangic_tarihi { get; set; }
        public Nullable<System.DateTime> uye_bitis_tarihi { get; set; }
        public Nullable<int> son_odeme_tipi_id { get; set; }
        public Nullable<System.Guid> inserted_by { get; set; }
        public Nullable<System.DateTime> inserted_at { get; set; }
        public Nullable<System.Guid> updated_by { get; set; }
        public string updated_at { get; set; }
        public Nullable<int> kalan_anket_sayisi { get; set; }
    }
}
