//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gnl_duyurular
    {
        public System.Guid duyuru_uid { get; set; }
        public Nullable<System.DateTime> duyuru_tarihi { get; set; }
        public string duyuru_basligi { get; set; }
        public string duyuru { get; set; }
        public Nullable<System.Guid> duyuru_olusturan_uid { get; set; }
        public Nullable<System.DateTime> duyuru_olusturma_tarihi { get; set; }
        public Nullable<int> duyuru_durumu_id { get; set; }
    }
}
