//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gnl_uyelik_aktivasyon_mail_gonderi_tarihcesi
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> paket_uid { get; set; }
        public string gonderilen_ad { get; set; }
        public string gonderilen_soyad { get; set; }
        public string gonderilen_email { get; set; }
        public Nullable<System.DateTime> gonderilme_tarihi { get; set; }
        public Nullable<System.Guid> gonderen_user_uid { get; set; }
    }
}
