//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_mail
    {
        public int id { get; set; }
        public string kime { get; set; }
        public string kimden { get; set; }
        public string gonderen_aktif_user_name { get; set; }
        public string tip { get; set; }
        public string subject { get; set; }
        public string mesaj { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
