//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbr_anket_yayinlama_mail_gonderi_aktivasyon
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> anket_uid { get; set; }
        public Nullable<System.Guid> tarihce_uid { get; set; }
        public string anket_gonderilen_ad { get; set; }
        public string anket_gonderilen_soyad { get; set; }
        public string anket_gonderilen_email { get; set; }
        public Nullable<System.DateTime> anket_gonderilme_tarihi { get; set; }
        public string anket_gonderilme_key { get; set; }
        public Nullable<bool> ankete_girildi { get; set; }
        public Nullable<System.DateTime> ankete_giris_tarihi { get; set; }
        public Nullable<bool> anket_bitirildi { get; set; }
        public Nullable<System.DateTime> anket_bitirilme_tarihi { get; set; }
        public Nullable<bool> ankete_cevap_verildi { get; set; }
        public Nullable<System.DateTime> ankete_cevap_verilme_tarihi { get; set; }
        public Nullable<System.Guid> anket_mail_grubu_uid { get; set; }
    }
}
