//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbr_anket_yayinlama_mail_gonderi_tarihcesi
    {
        public System.Guid tarihce_uid { get; set; }
        public Nullable<System.Guid> anket_uid { get; set; }
        public Nullable<System.Guid> gonderilen_mail_grubu_uid { get; set; }
        public Nullable<System.DateTime> gonderi_tarihi { get; set; }
        public Nullable<System.Guid> gonderen_user_uid { get; set; }
        public string gonderilen_mail_konusu { get; set; }
        public string gonderilen_mail { get; set; }
        public string host_name { get; set; }
        public string user_host_adres { get; set; }
    }
}
