//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbr_anket_yayinlama_mail_gonderi_kisi_tarihcesi
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> tarihce_uid { get; set; }
        public string gonderilen_kisi_ismi { get; set; }
        public string gonderilen_email_adresi { get; set; }
    }
}
