//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbr_anket_yayinlama_acik_anket_aktivasyon
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> anket_uid { get; set; }
        public string giris_key { get; set; }
        public Nullable<bool> anket_bitirildi { get; set; }
        public Nullable<System.DateTime> anket_bitirilme_tarihi { get; set; }
        public string host_name { get; set; }
        public string user_host_adres { get; set; }
        public string browser { get; set; }
        public string platform { get; set; }
        public string versiyon { get; set; }
    }
}
