//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbr_soru_tipi_6_secenekleri
    {
        public System.Guid soru_secenek_uid { get; set; }
        public Nullable<System.Guid> soru_uid { get; set; }
        public string soru_secenek_ad { get; set; }
        public Nullable<int> soru_secenek_sira_no { get; set; }
    }
}
