//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbr_mail_gruplari_kullanici_listesi
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> mail_grubu_uid { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string email { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
        public Nullable<System.DateTime> olusturma_tarihi { get; set; }
        public Nullable<System.Guid> olusturan_kullanici_uid { get; set; }
    }
}
