//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbr_soru_tipi_2_cevaplari
    {
        public System.Guid id { get; set; }
        public string cevap_key { get; set; }
        public Nullable<System.Guid> soru_uid { get; set; }
        public Nullable<System.Guid> soru_secenek_uid { get; set; }
        public Nullable<bool> cevap { get; set; }
        public string cevaplayan_ad { get; set; }
        public string cevaplayan_soyad { get; set; }
        public string cevaplayan_email { get; set; }
        public Nullable<System.DateTime> cavaplama_tarihi { get; set; }
        public string session_id { get; set; }
        public string host_name { get; set; }
        public string user_host_adres { get; set; }
        public string browser { get; set; }
        public string platform { get; set; }
        public string version { get; set; }
    }
}
